name: Auto Publish Pre-release Extension

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.json'
      - '**.ts'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install vsce
        run: npm i -g @vscode/vsce

      - name: Install web-tree-sitter
        run: npm i web-tree-sitter

      - name: Publish Pre-release
        run: |
          git config --global user.name "RedCMD"
          git config --global user.email "theredcmd@gmail.com"
          vsce publish patch --pre-release -p ${{ secrets.VSCE_PAT }} --skip-duplicate
          git push
