name: Publish Pre-release Extension

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**.json'
      - '**.ts'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install vsce
        run: npm i -g @vscode/vsce

      - name: Install web-tree-sitter
        run: npm i web-tree-sitter

      - name: Install vscode-oniguruma
        run: npm i vscode-oniguruma@1.7.0 -E

      - name: Publish Pre-release
        run: |
          git config --global user.name "RedCMD"
          git config --global user.email "theredcmd@gmail.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Sync Github Actions"
          vsce publish patch --pre-release -p ${{ secrets.VSCE_PAT }}
          git push
