name: Publish Pre-release Extension

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.tmLanguage.json'
      - '**.language-configuration.json'
      - '**.ts'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies # vsce etc
        run: | # shell
          npm i

      - name: Build Extension # build `extension.js` and `*.wasm` files
        run: | # shell
          npm run build

      - name: Setup Github Actions # allow use of `git push`
        run: | # shell
          git config --global user.name "RedCMD"
          git config --global user.email "theredcmd@gmail.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Sync Github Actions"

      - name: Publish Pre-release # upload to Extension Marketplace
        run: | # shell
          npx vsce publish patch --pre-release
          git push --follow-tags
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
